### ISSUE TITLE
A couple dozen typos in the code. 

### ISSUE THREAD

**Issue by elvey** [BcBowe3/Breakthrough#2]
I created a pull request with two patches to fix 'em: #1 

A step to make it more comprehensible. 
(Possibly significant changes to lines 10,11.) 
Please review and pull/merge. 
Where is "outside program"?

**Comment by BcBowe3** [comment]
Thank you! I am rather new to github, but will do my best to review. 

We will not be providing the code for the determination of the high dimeinosal covariates, but please refer to Schneeweiss, S., Rassen, J. A., Glynn, R. J., Avorn, J., Mogun, H., & Brookhart, M. A. (2009). High-dimensional propensity score adjustment in studies of treatment effects using health care claims data. Epidemiology (Cambridge, Mass.), 20(4), 512.
